name: 'Review PR Action'
description: 'An action to review pull requests using OpenAI'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API key'
    required: true
  OPENAI_API_MODEL:
    description: 'OpenAI API model'
    required: true
  prompt_template:
    description: 'Template for the review prompt'
    required: true
# ... autres configurations ...
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
